
// //REDUCERS
export const USER_REDUCER = "USER_REDUCER"

//SERVICES
export const USER_SERVICES = "USER_SERVICES"


//USERS
export const ALL_PROVIDERS = "ALL_PROVIDERS"


//REQUESTS
// export const CREATE_REQUEST = "CREATE_REQUEST"
// export const UPDATE_REQUEST = "UPDATE_REQUEST"
// export const PROVIDER_REQUESTS = "PROVIDER_REQUESTS"
